branchName: full
silent: false
commentMessage: "Begin development on this branch by running the following commands in the root directory of your local copy of the repository:\n\n`git pull`\n`git switch ${branchName}`"
