name: CI

on:
  push:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'
  pull_request:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.tup
            ~/build
            !~/build/Tupfile
          key: ${{ runner.os }}-cache

      - name: Install tools and dependencies
        run: |
          sudo apt-get install -y tup libglfw3-dev libvulkan-dev libxi-dev libxxf86vm-dev

      - name: Initialize tup if not cached
        if: steps.cache.outputs.cache-hit != 'true'
        run: tup init

      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Run tup to build
        run: |
          tup

#      - name: Run tests
#        run: test/facade_test
