name: CI

on:
  push:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'
  pull_request:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-lld
            mingw-w64-x86_64-libc++
            mingw-w64-x86_64-libc++abi
            mingw-w64-clang-x86_64-winpthreads-git
            msys2-runtime-devel
            base-devel
            libreadline-devel

      - name: Install tools and dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y tup libvulkan-dev libxi-dev libxxf86vm-dev libreadline-dev xorg-dev lcov
          mkdir external/glslc
          cd external/glslc
          curl -fsS "https://storage.googleapis.com/shaderc/badges/build_link_linux_clang_release.html" | awk -v 'RS=<' -F\> '/^meta http-equiv="refresh"/ && $1 ~ /url=/{split($1,a,"[?=\"]");exit} END{print "url=\""a[7]"\""}' | curl -f --remote-name-all -K-
          tar -xf install.tgz

      - name: Install tools and dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl http://gittup.org/tup/win32/tup-latest.zip -o tup.zip
          7z x -bso0 -bsp0 tup.zip
          mkdir external/glslc
          cd external/glslc
          curl -fsS "https://storage.googleapis.com/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/windows/continuous_release_2017/374/20210924-175819/install.zip"
          7z x -bso0 -bsp0 install.zip

      - name: Install Vulkan SDK (Windows)
        if: matrix.os == 'windows-latest'
        uses: humbletim/setup-vulkan-sdk@v1.0.3

      - name: Update submodules
        run: |
          git submodule init
          git submodule update
          git submodule status external/lua >luastatus
          git submodule status external/yaml-cpp >yaml-cppstatus
          git submodule status external/glfw >glfwstatus
          git submodule status external/sqlite >sqlitestatus

      - name: Cache Handling (lua)
        id: cache-lua
        uses: actions/cache@v2
        with:
          path: |
            external/lua/liblua.a
          key: ${{ runner.os }}-lua-1-${{ hashFiles('luastatus') }}

      - name: Cache Handling (yaml-cpp)
        id: cache-yaml
        uses: actions/cache@v2
        with:
          path: |
            external/yaml-cpp/libyaml-cpp.a
            external/yaml-cpp/include/yaml-cpp/dll.h
          key: ${{ runner.os }}-yaml-cpp-1-${{ hashFiles('yaml-cppstatus') }}

      - name: Cache Handling (GLFW, Ubuntu)
        if: matrix.os != 'windows-latest'
        id: cache-glfw
        uses: actions/cache@v2
        with:
          path: |
            external/glfw/src/libglfw3.a
          key: ${{ runner.os }}-glfw-2-${{ hashFiles('glfwstatus') }}

      - name: Build Lua Library (Ubuntu)
        if: (steps.cache-lua.outputs.cache-hit != 'true') && (matrix.os == 'ubuntu-latest')
        run: |
          cd external/lua
          sed -i 's/CC= gcc/CC= g++/g' makefile
          make all
          cd ../..

      - name: Build Lua Library (Windows)
        if: (steps.cache-lua.outputs.cache-hit != 'true') && (matrix.os == 'windows-latest')
        shell: msys2 {0}
        run: |
          cd external/lua
          sed -i 's/CC= gcc/CC= clang++/g' makefile
          sed -i 's/AR= ar rc/AR= llvm-ar rc/g' makefile
          sed -i 's/RANLIB= ranlib/RANLIB= llvm-ranlib/g' makefile
          sed -i 's/-std=c99 -DLUA_USE_LINUX -DLUA_USE_READLINE/-DLUA_USE_WINDOWS/g' makefile
          sed -i 's/-ldl -lreadline//g' makefile
          sed -i 's/	-Wlogical-op \\//g' makefile
          sed -i 's/	-Wno-aggressive-loop-optimizations \\//g' makefile
          make all
          cd ../..

      - name: Build YAML Library (Ubuntu)
        if: (steps.cache-yaml.outputs.cache-hit != 'true') && (matrix.os == 'ubuntu-latest')
        run: |
          cd external/yaml-cpp
          cmake .
          make yaml-cpp
          cd ../..

      - name: Build YAML Library (Windows)
        if: (steps.cache-yaml.outputs.cache-hit != 'true') && (matrix.os == 'windows-latest')
        shell: msys2 {0}
        run: |
          cd external/yaml-cpp
          echo $path
          export CC=/mingw64/bin/clang.exe
          export CXX=/mingw64/bin/clang++.exe
          cmake -G "MSYS Makefiles" -D_CMAKE_TOOLCHAIN_PREFIX=llvm- .
          make yaml-cpp
          cd ../..

      - name: Fetch SQLite3 Library (Ubuntu)
        run: |
          cd external
          curl https://www.sqlite.org/2021/sqlite-amalgamation-3360000.zip -o sql.zip
          7z x -bso0 -bsp0 sql.zip
          mv sqlite-amalgamation-3360000 sqlite-build

      - name: Build GLFW Library (Ubuntu)
        if: (steps.cache-glfw.outputs.cache-hit != 'true') && (matrix.os == 'ubuntu-latest')
        run: |
          cd external/glfw
          cmake -DBUILD_SHARED_LIBS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
          make glfw
          cd ../..

      - name: Run tup to build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          tup

      - name: Run tup to build (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          ./tup

      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir /home/runner/.local
          mkdir /home/runner/.local/share
          test/test
          cat test/test.log
          cd gcov
          gcov -o ../test ../src/*.cc -t >test.gcov
          lcov -c -d ../test -o test.info
          lcov -e test.info /home/runner/work/nebula/nebula/src/* -o test.info

      - name: Run tests (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: |
          test/test
          cat test/test.log
          cd gcov
          gcov -o ../test ../src/*.cc -t >test.gcov
          lcov -c -d ../test -o test.info
          lcov -e test.info /home/runner/work/nebula/nebula/src/* -o test.info

      - uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: gcov/test.info
          name: codecov-nebula
          fail_ci_if_error: false
          verbose: true
