name: CI

on:
  push:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'
  pull_request:
    paths:
    - '**.cc'
    - '**.h'
    - '**Tupfile'
    - 'Tuprules.tup'
    - '.github/workflows/continuous-integration.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tup libglfw3-dev libvulkan-dev libxi-dev libxxf86vm-dev libreadline-dev

      - name: Update submodules
        run: |
          git submodule init
          git submodule update
          git submodule status external/lua >luastatus
          git submodule status external/yaml-cpp >yaml-cppstatus

      - name: Cache Handling (lua)
        id: cache-lua
        uses: actions/cache@v2
        with:
          path: |
            external/lua/liblua.a
          key: ${{ runner.os }}-${{ hashFiles('luastatus') }}

      - name: Cache Handling (yaml-cpp)
        id: cache-yaml
        uses: actions/cache@v2
        with:
          path: |
            external/yaml-cpp/libyaml-cpp.a
          key: ${{ runner.os }}-${{ hashFiles('yaml-cppstatus') }}

      - name: Build Lua Library
        if: steps.cache-lua.outputs.cache-hit != 'true'
        run: |
          cd external/lua
          make all
          cd ../..

      - name: Build YAML Library
        if: steps.cache-yaml.outputs.cache-hit != 'true'
        run: |
          cd external/yaml-cpp
          cmake .
          make
          cd ../..

      - name: Run tup to build
        run: |
          tup

      - name: Run tests
        run: test/test
