# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Handle Stale Issues/PRs

on:
  schedule:
  - cron: '16 7 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 49
        days-before-close: 7
        stale-issue-message: 'No activity on this issue. Marking it as stale. Update within 7 days or it will be closed.'
        stale-pr-message: 'No activity on this pull request. Marking it as stale. Update within 7 days or it will be closed.'
        close-issue-message: 'No activity on this stale issue in the past 7 days. Closing.'
        close-pr-message: 'No activity on this stale pull request in the past 7 days. Closing.'
        stale-issue-label: 'stale'
        close-issue-label: 'auto-closed'
        stale-pr-label: 'stale'
        close-pr-label: 'auto-closed'
